application: georemindme
version: 3
runtime: python
api_version: 1


handlers:
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/webapp/img/favicon.png
  upload: static/webapp/img/favicon.png

- url: /static
  static_dir: static

- url: /ajax/.*
  script: main.py
  secure: optional

- url: /api/(.*)
  script: service/api/main.py
  secure: always

- url: /admin/(.*)
  script: appengine_admin/main.py
  secure: always
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: always 
  
- url: /test.*
  script: gaeunit/gaeunit.py
  
- url: /.*
  script: main.py
  secure: optional

builtins:
- appstats: on
- deferred: on

#inbound_services:
#- warmup
