application: georemindme
version: live
runtime: python
api_version: 1

default_expiration: "0d"


handlers:
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /sitemap.xml
  script: sitemap.py  

- url: /favicon.ico
  static_files: static/webapp/img/favicon.png
  upload: static/webapp/img/favicon.png

- url: /static
  static_dir: static

- url: /ajax/.*
  script: main.py
  secure: optional

- url: /api/(.*)
  script: service/api/main.py
  secure: optional

- url: /admin/(.*)
  script: appengine_admin/main.py
  secure: always
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: always 
  
- url: /test.*
  script: gaeunit/gaeunit.py
  login: admin
  
- url: /_ah/queue/deferred
  script: maindeferred.py
  login: admin
  
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
#login: admin
  
- url: /.*
  script: main.py
  secure: always
  

builtins:
- appstats: on
#- remote_api: on

inbound_services:
- warmup
