application: georemindme-hrd
version: live
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"


handlers:
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/webapp/img/favicon.png
  upload: static/webapp/img/favicon.png

- url: /static
  static_dir: static
  secure: always

- url: /ajax/.*
  script: main.app
  secure: optional

- url: /api/.*
  script: service.app
  secure: always
  
- url: /suggestion/.*
  script: main.app
  secure: never
  
- url: /place/.*
  script: main.app
  secure: never
  
- url: /.*
  script: main.app
  secure: always
  

builtins:
#- appstats: on
#- remote_api: on
#- deferred: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.2" 
