application: georemindme-hrd
version: live
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"


handlers:
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/webapp/img/favicon.png
  upload: static/webapp/img/favicon.png

- url: /static
  static_dir: static
  secure: always

- url: /api/.*
  script: service.app
  secure: always
  
- url: /ajax/.*
  script: main.app
  secure: optional

- url: /suggestion/.*
  script: main.app
  secure: never
  
- url: /place/.*
  script: main.app
  secure: never
  
- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
  
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin
  secure: always
  
- url: /console.*
  script: google.appengine.ext.admin.application
  secure: always
  login: admin

- url: /test/.*
  script: main.app
  secure: always
  login: admin
  
- url: /_ah/stats/.*
  script: google.appengine.appstats.application
  secure: always
  login: admin
  
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.handler.application
  login: admin
  
- url: /.*
  script: main.app
  secure: always
  
skip_files:
- ^(.*/)?app\.yaml


builtins:
#- appstats: on
#- remote_api: on
#- deferred: on

inbound_services:
- warmup

libraries:
- name: django
  version: "1.2" 
  
- name: webapp2
  version: "latest"
