application: georemindme
version: 1
runtime: python
api_version: 1


handlers:
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/webapp/img/favicon.png
  upload: static/webapp/img/favicon.png

- url: /static
  static_dir: static

- url: /ajax/.*
  script: main.py
  secure: optional

- url: /service/.*
  script: main.py
  secure: always

- url: /dashboard/.*
  script: main.py
  secure: always

- url: /admin(.*)
  script: appengine_admin/main.py
  secure: always
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: always 
  
- url: /test.*
  script: gaeunit/gaeunit.py
  
- url: /.*
  script: main.py
  secure: optional
  
- url: /media/admin
  static_dir: django/contrib/admin/media/
  expiration: '0'

- url: /media
  static_dir: _generated_media/
  expiration: '365d'

builtins:
- appstats: on
- deferred: on

#inbound_services:
#- warmup
