<?php
	$menu_sections=array(
		array(
			'name'=>'Home',
			'url'=>'http://www.georemindme.com',
		),
		array(
			'name'=>'APIs',
			'url'=>'http://api.georemindme.com',
		),
		array(
			'name'=>'Community',
			'url'=>'http://team.georemindme.com',
		),
		array(
			'name'=>'Jobs',
			'url'=>'http://jobs.georemindme.com',
		),
	)
?>
