application: georemindme
version: 4
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /static
  static_dir: static
  secure: optional
  
- url: /ajax/login/
  script: main.py
  secure: optional

- url: /ajax/register/
  script: main.py
  secure: optional

- url: /ajax/exists/
  script: main.py
  secure: optional

- url: /ajax/keep-up-to-date/
  script: main.py
  secure: optional

- url: /ajax/.*
  script: main.py
  secure: always

- url: /dashboard/.*
  script: main.py
  secure: always

- url: /.*
  script: main.py
  secure: optional



builtins:
- datastore_admin: on
  
