application: georemindme
version: 3
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /appengine_admin_media
  static_dir: appengine_admin/media
  secure: always

- url: /static
  static_dir: static

- url: /ajax/.*
  script: main.py
  secure: optional
  
- url: /service/.*
  script: main.py
  secure: optional

- url: /dashboard/.*
  script: main.py
  secure: always

- url: /admin(.*)
  script: appengine_admin/main.py
  secure: always
  
- url: /.*
  script: main.py
  secure: optional


builtins:
- datastore_admin: on
- appstats: on

inbound_services:
- warmup
